version: "3.9"
services:
  postgres_db:
    image: postgres
    command: -p 5434
    env_file:
      - backend/.env
    environment:
      - POSTGRES_HOST=postgres_db
      - POSTGRES_PORT=5434
    expose:
      - 5434
    ports:
      - "5434:5434"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  redis:
    image: "redis:alpine"
    expose:
      - 6379
    ports:
      - "6379:6379"
  celery:
    build: 
      context: .
      dockerfile: ./docker/celery/Dockerfile
    image: shoonya-backend_celery
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres_db
      - redis
  web:
    build:
      context: .
      dockerfile: ./docker/django-rest-api/Dockerfile
    image: shoonya-backend
    env_file:
      - backend/.env
    ports:
      - "8000:8000"
    volumes:
       - .:/usr/src/app
    depends_on:
      - postgres_db
      - celery

volumes:
  postgres_data: