version: "3.9"
services:
  web:
    depends_on:
      - postgres_db
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: shoonya-backend
    env_file:
      - backend/.env.prod
    ports:
      - "8000:8000"
    command: sh /app/entrypoint.sh
    volumes:
       - ./backend:/app/
    depends_on:
      - celery
  postgres_db:
    image: postgres
    command: -p 5434
    env_file:
      - backend/.env
    environment:
      - POSTGRES_HOST=postgres_db
      - POSTGRES_PORT=5434
    expose:
      - 5434
    ports:
      - "5434:5434"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  redis:
      image: "redis:alpine"
      expose:
        - 6379
      ports:
        - "6379:6379"
  celery:
    build: 
      context: .
      dockerfile: k8s/celery/Dockerfile
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres_db
      - redis

volumes:
  postgres_data: