# Generated by Django 3.2.14 on 2025-04-30 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0060_auto_20241029_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('ModelOutputEvaluation', 'ModelOutputEvaluation'), ('ModelInteractionEvaluation', 'ModelInteractionEvaluation'), ('MultipleInteractionEvaluation', 'MultipleInteractionEvaluation'), ('InstructionDrivenChat', 'InstructionDrivenChat'), ('MultipleLLMInstructionDrivenChat', 'MultipleLLMInstructionDrivenChat')], help_text='Project Type indicating the annotation task', max_length=100),
        ),
    ]
