# Generated by Django 5.1.11 on 2026-03-06 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0063_projectbookmark"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="preferred_annotators",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of preferred annotator user IDs for review task pulling",
            ),
        ),
    ]
