# Generated by Django 5.1.11 on 2026-04-09 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0063_projectbookmark"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="max_Draft_tasks_per_user",
            field=models.IntegerField(
                default=60,
                help_text="Maximum no. of Draft task in project",
                verbose_name="max_Draft_tasks_per_user",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="max_Skipped_tasks_per_user",
            field=models.IntegerField(
                default=60,
                help_text="Maximum no. of Skipped task in project",
                verbose_name="max_Skipped_tasks_per_user",
            ),
        ),
    ]
