# Generated by Django 5.1.11 on 2026-03-06 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0064_project_preferred_annotators"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="preferred_annotators",
            field=models.JSONField(
                blank=True,
                default=None,
                help_text="List of preferred annotator user IDs for review task pulling. null=never set, []=deliberately empty",
                null=True,
            ),
        ),
    ]
