# Generated by Django 5.1.11 on 2025-12-05 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0050_alter_annotation_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="annotation",
            name="previous_annotations_json",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Stores previous versions of this annotation's result when it goes through revision/rejection cycles",
                null=True,
                verbose_name="previous_annotations_json",
            ),
        ),
    ]
