# Generated by Django 5.1.11 on 2026-05-24 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0039_alter_user_preferred_task_by_json"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="prefer_cl_ui",
        ),
    ]
