# Generated by Django 5.1.11 on 2026-04-29 09:07

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0039_alter_user_preferred_task_by_json"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="annotation_ui_preferences",
            field=models.JSONField(
                blank=True,
                default=users.models.default_annotation_ui_preferences,
                help_text="Stores annotation page UI preferences: instruction panel width, font size, and pinned state.",
                null=True,
            ),
        ),
    ]
