# Generated by Django 3.2.14 on 2026-03-01 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_alter_user_preferred_task_by_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Prefered_Workspace',
            field=models.JSONField(blank=True, default=dict, help_text='Indicates the preferred workspace of the user', null=True, verbose_name='workspace_prefered'),
        ),
    ]
