# Generated by Django 5.1.11 on 2026-04-30 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0040_user_annotation_ui_preferences"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="prefer_cl_ui",
        ),
    ]
