name: run-linters
on: [pull_request]
jobs:          
  run-black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.9.21
        uses: actions/setup-python@v1
        with:
          python-version: 3.9.21
      - name: Debug Message - Check Github branch
        run: echo "Current Git branch is ${GITHUB_REF##*/}" 
      - name: Install Black
        run: pip install black==23.1.0
      - name: Run black . to format code.
        run: black .
